"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, Loader2 } from "lucide-react";

type Service={id:string;name:string;description?:string;durationMin:number;priceCents:number;active:boolean};
export default function AgendarPage(){
 const [sent,setSent]=useState(false);const [services,setServices]=useState<Service[]>([]);const [loading,setLoading]=useState(true);const [serviceError,setServiceError]=useState("");
 useEffect(()=>{(async()=>{try{const r=await fetch('/api/services',{cache:'no-store'});if(!r.ok)throw new Error();setServices(await r.json())}catch{setServiceError('Não foi possível carregar os serviços. Atualize a página e tente novamente.')}finally{setLoading(false)}})()},[]);
 if(sent) return <main className="shell"><div className="form-card" style={{textAlign:"center"}}><CheckCircle2 size={48} style={{margin:"0 auto 18px"}}/><div className="eyebrow">Tudo certo</div><h1 style={{fontSize:42}}>Agendamento solicitado</h1><p className="section-copy" style={{margin:"0 auto 24px"}}>Seu pedido foi registrado. A próxima etapa conectará a disponibilidade real da agenda da Clicia.</p><Link className="btn btn-primary" href="/">Voltar ao início</Link></div></main>;
 return <main className="shell"><div className="form-card"><Link href="/" style={{display:"inline-flex",gap:8,alignItems:"center",color:"var(--muted)"}}><ArrowLeft size={16}/> Voltar</Link><div className="eyebrow" style={{marginTop:28}}>Agendamento</div><h1 style={{fontSize:46}}>Reserve seu horário</h1><form onSubmit={(e)=>{e.preventDefault();setSent(true)}}><div className="field"><label>Serviço</label><select required defaultValue="" disabled={loading||!!serviceError}><option value="" disabled>{loading?'Carregando serviços...':'Selecione um serviço'}</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} — R$ {(s.priceCents/100).toFixed(2).replace('.',',')}</option>)}</select>{loading&&<span style={{display:'flex',gap:7,alignItems:'center',fontSize:13}}><Loader2 size={14}/> Buscando serviços disponíveis...</span>}{serviceError&&<p style={{color:'#9b3030',fontSize:13}}>{serviceError}</p>}{!loading&&!serviceError&&services.length===0&&<p style={{fontSize:13}}>Nenhum serviço disponível no momento.</p>}</div><div className="field"><label>Data</label><input required type="date" /></div><div className="field"><label>Horário</label><select required defaultValue=""><option value="" disabled>Selecione o horário</option><option>09:00</option><option>10:00</option><option>11:00</option><option>14:00</option><option>15:00</option></select></div><div className="field"><label>Nome</label><input required placeholder="Seu nome" /></div><div className="field"><label>WhatsApp</label><input required inputMode="tel" placeholder="(11) 99999-9999" /></div><div className="field"><label>Observação (opcional)</label><textarea rows={3} placeholder="Alguma informação importante?" /></div><button className="btn btn-primary" style={{width:"100%"}} type="submit" disabled={loading||services.length===0}><CalendarDays size={17}/> Confirmar agendamento</button></form></div></main>
}
